const STOP_HOOK_UNLOCK_ARTIFACT = {
  kind: "prompt",
  title: "Claude Code용 OMX 스타일 계속진행 Stop hook 생성 프롬프트",
  body: [
    "Claude Code용 OMX 스타일 계속진행 Stop hook 설정과 예제 스크립트를 만들어줘.",
    "추가로 Codex 프로젝트 로컬 Stop hook에서도 같은 상태 파일을 재사용할 수 있게 래퍼를 분리해줘.",
    "",
    "중요:",
    "- Claude Code와 Codex의 Stop hook 출력 스키마를 분리한다.",
    "- Claude Code allow 출력은 { \"decision\": \"allow\" } 형식을 사용한다.",
    "- Codex allow 출력은 { \"continue\": true } 형식으로 정규화한다.",
    "- block 출력은 둘 다 { \"decision\": \"block\", \"reason\": \"검증 증거가 부족합니다\", \"continue\": false } 계열을 사용할 수 있게 하되, Codex 래퍼가 최종 스키마를 보정한다.",
    "- hook stdout에는 반드시 단일 JSON 한 줄만 출력한다.",
    "- 로그, 디버그, 검증 명령 출력은 stderr로만 보낸다.",
    "",
    "참고한 설계:",
    "- Yeachan-Heo/oh-my-codex의 native Stop continuation 아이디어를 참고한다.",
    "- Stop hook은 작업이 끝났는지 묻는 검문소가 아니라, 남은 작업이 있으면 block으로 계속 진행하게 하는 장치다.",
    "- 상태는 processing, finished, blocked, failed, askuserQuestion lifecycle을 구분한다.",
    "",
    "목표:",
    "- 새 사용자 요청이 들어오면 작업 상태를 processing으로 기록한다.",
    "- Claude가 답변을 끝내기 직전에는 Stop hook이 완료 증거를 검사한다.",
    "- 완료 증거가 부족하면 block으로 멈춤을 막고 계속 작업하게 한다.",
    "- 완료 증거가 충분하면 status를 finished로 바꾸고 Stop hook이 통과하게 한다.",
    "- status가 finished이면 Stop hook은 다시 block하지 않는다.",
    "- 사용자의 추가 판단이 필요하면 askuserQuestion 상태로 바꾸고 block하지 않는다.",
    "- hook payload에 마지막 응답이나 transcript_path가 없으면 무조건 block하지 말고, 런타임별 fallback 정책을 둔다.",
    "",
    "만들 파일:",
    "- .claude/settings.local.json",
    "- .claude/settings.local.example.json",
    "- scripts/agent-status-start.js",
    "- scripts/agent-stop-check.js",
    "- .agent-status.example.json",
    "- Codex 변형이 필요하면 .codex/hooks.json, .codex/stop-hook.js",
    "",
    "UserPromptSubmit hook:",
    "- 새 요청을 받으면 .agent-status.json을 만든다.",
    "- status는 processing으로 둔다.",
    "- attempts는 0으로 초기화한다.",
    "- max_block_attempts는 3으로 둔다.",
    "- stop_hook_active는 false로 둔다.",
    "- started_at은 ISO 날짜로 둔다.",
    "- 기존 finished 상태가 있더라도 새 사용자 요청이면 processing으로 갱신한다.",
    "",
    "Stop hook:",
    "- .agent-status.json이 없으면 안전하게 processing 상태를 만든다.",
    "- status가 finished, blocked, failed, askuserQuestion 중 하나이면 allow로 통과한다.",
    "- status가 processing이면 마지막 응답과 검증 로그를 확인한다.",
    "- hook payload에서 transcript_path 또는 마지막 응답을 찾을 수 있으면 그 내용을 검사한다.",
    "- hook payload가 비어 있는 런타임에서는 설정 가능한 fallback을 사용한다.",
    "- 테스트/검증/남은 위험 보고가 부족하면 block과 이유를 반환한다.",
    "- 완료 증거가 충분하면 status를 finished로 저장하고 allow를 반환한다.",
    "- 외부 입력이 필요하면 status를 askuserQuestion으로 저장하고 allow를 반환한다.",
    "",
    "loop guard:",
    "- stop_hook_active가 true이면 중복 검문을 막고 allow한다.",
    "- attempts를 block할 때마다 증가시킨다.",
    "- attempts가 max_block_attempts에 도달하면 더 이상 block하지 말고 status를 blocked로 저장한 뒤 allow한다.",
    "- blocked 상태에서는 최종 응답에서 남은 위험과 미완료 검증을 보고하게 한다.",
    "",
    "검증 기준:",
    "- node --check scripts/agent-status-start.js",
    "- node --check scripts/agent-stop-check.js",
    "- Claude용 allow/block JSON 출력 확인",
    "- Codex용 allow/block JSON 출력 확인",
    "- stdout이 단일 JSON 한 줄인지 확인",
    "- .agent-status.json에 API key, 개인 경로, 민감 로그가 저장되지 않는지 확인",
    "",
    "주의:",
    "- 항상 block하는 Stop hook을 만들지 마라.",
    "- finished, blocked, failed, askuserQuestion 상태에서는 반드시 통과해야 한다.",
    "- 프로젝트별 테스트 명령은 상단 상수로 분리해라.",
    "- 상태 파일에는 민감정보를 저장하지 마라.",
    "- .agent-status.json은 런타임 파일이므로 gitignore에 넣고, 공유용 예시는 .agent-status.example.json으로 둔다.",
  ].join("\n"),
};

function buildUnlockArtifact(practice) {
  if (practice.id !== "act6-stop-hook-gate") return undefined;
  return { ...STOP_HOOK_UNLOCK_ARTIFACT };
}

module.exports = {
  buildUnlockArtifact,
};
