const STOP_HOOK_UNLOCK_ARTIFACT = {
  kind: "prompt",
  title: "Claude Code용 OMX 스타일 계속진행 Stop hook 생성 프롬프트",
  body: [
    "Claude Code용 OMX 스타일 계속진행 Stop hook 설정과 예제 스크립트를 만들어줘.",
    "",
    "참고한 설계:",
    "- Yeachan-Heo/oh-my-codex의 native Stop continuation 아이디어를 참고한다.",
    "- Stop hook은 작업이 끝났는지 묻는 검문소가 아니라, 남은 작업이 있으면 decision: \"block\"으로 계속 진행하게 하는 장치다.",
    "- 상태는 finished, blocked, failed, askuserQuestion 같은 terminal lifecycle을 구분한다.",
    "",
    "목표:",
    "- 새 사용자 요청이 들어오면 작업 상태를 processing으로 기록한다.",
    "- Claude가 답변을 끝내기 직전에는 Stop hook이 완료 증거를 검사한다.",
    "- 완료 증거가 부족하면 decision: \"block\"으로 멈춤을 막고 계속 작업하게 한다.",
    "- 완료 증거가 충분하면 status를 finished로 바꾸고 Stop hook이 통과하게 한다.",
    "- status가 finished이면 Stop hook은 다시 block하지 않는다.",
    "- 사용자의 추가 판단이 필요하면 askuserQuestion 상태로 바꾸고 block하지 않는다.",
    "",
    "필수 Hook 구조:",
    "1. UserPromptSubmit hook",
    "   - 새 요청을 받으면 .agent-status.json을 만든다.",
    "   - status는 processing으로 둔다.",
    "   - attempts는 0으로 초기화한다.",
    "   - max_block_attempts는 3으로 둔다.",
    "   - stop_hook_active는 false로 둔다.",
    "2. Stop hook",
    "   - .agent-status.json을 읽는다.",
    "   - status가 finished, blocked, failed, askuserQuestion 중 하나이면 allow로 통과한다.",
    "   - status가 processing이면 마지막 응답과 검증 로그를 확인한다.",
    "   - 테스트/검증/남은 위험 보고가 부족하면 decision: \"block\"과 이유를 반환한다.",
    "   - 완료 증거가 충분하면 status를 finished로 저장하고 통과한다.",
    "   - 외부 입력이 필요하면 status를 askuserQuestion으로 저장하고 통과한다.",
    "3. loop guard",
    "   - stop_hook_active가 true이면 중복 검문을 막는다.",
    "   - attempts가 max_block_attempts를 넘으면 block 대신 status를 blocked로 저장하고 남은 위험을 보고하게 한다.",
    "",
    "만들 파일:",
    "- .claude/settings.local.json",
    "- scripts/agent-status-start.js",
    "- scripts/agent-stop-check.js",
    "- .agent-status.json 예시",
    "",
    "settings.local.json 예시 요구사항:",
    "- UserPromptSubmit에서 node scripts/agent-status-start.js 실행",
    "- Stop에서 node scripts/agent-stop-check.js 실행",
    "- Stop hook 결과는 JSON으로 반환",
    "",
    "agent-status-start.js 요구사항:",
    "- 현재 작업 상태 파일을 .agent-status.json에 저장",
    "- { status: \"processing\", attempts: 0, max_block_attempts: 3, stop_hook_active: false, started_at: ISO 날짜 } 형태 사용",
    "- 기존 finished 상태가 있더라도 새 사용자 요청이면 processing으로 갱신",
    "",
    "agent-stop-check.js 요구사항:",
    "- .agent-status.json이 없으면 안전하게 processing 상태를 만든다.",
    "- stop_hook_active를 true로 바꾼 뒤 검사를 시작하고, 종료 시 false로 되돌린다.",
    "- 마지막 응답에 검증 명령, 결과, 남은 위험 보고가 있는지 검사한다.",
    "- 부족하면 { decision: \"block\", reason: \"검증 명령 결과와 남은 위험 보고가 없어 완료를 막습니다.\" }를 출력한다.",
    "- 충분하면 status를 finished로 저장하고 { decision: \"allow\" }를 출력한다.",
    "- 사용자 질문이 필요하면 status를 askuserQuestion으로 저장하고 { decision: \"allow\" }를 출력한다.",
    "- attempts 증가와 max_block_attempts 기반 반복 제한을 포함한다.",
    "",
    "주의:",
    "- 항상 block하는 Stop hook을 만들지 마라.",
    "- finished, blocked, failed, askuserQuestion 상태에서는 반드시 통과해야 한다.",
    "- 프로젝트별 테스트 명령은 나중에 바꿀 수 있게 상단 상수로 분리해라.",
    "- API key, 개인 경로, 민감한 로그는 상태 파일에 저장하지 마라.",
  ].join("\n"),
};

function buildUnlockArtifact(practice) {
  if (practice.id !== "act6-stop-hook-gate") return undefined;
  return { ...STOP_HOOK_UNLOCK_ARTIFACT };
}

module.exports = {
  buildUnlockArtifact,
};
