const STOP_HOOK_UNLOCK_ARTIFACT = {
  kind: "prompt",
  title: "Claude Code용 OMX 스타일 계속진행 Stop hook 생성 프롬프트",
  body: [
    "Claude Code용 OMX 스타일 계속진행 Stop hook 설정과 예제 스크립트를 만들어줘.",
    "추가로 Codex 프로젝트 로컬 Stop hook에서도 같은 상태 파일과 공용 검사기를 재사용하되, 런타임별 최종 stdout 스키마는 래퍼에서 분리해줘.",
    "",
    "중요:",
    "- Claude Code와 Codex의 Stop hook 최종 stdout 스키마를 절대 섞지 않는다.",
    "- Claude Code allow stdout은 { \"decision\": \"allow\" } 한 줄만 사용한다.",
    "- Codex allow stdout은 { \"continue\": true } 한 줄만 사용한다.",
    "- Claude Code block stdout은 { \"decision\": \"block\", \"reason\": \"검증 증거가 부족합니다\", \"continue\": false } 형식을 사용할 수 있다.",
    "- Codex block stdout은 { \"decision\": \"block\", \"reason\": \"검증 증거가 부족합니다\" } 형식으로 보정한다.",
    "- Codex 최종 stdout에는 decision:allow, continue:false, systemMessage를 넣지 않는다.",
    "- 공용 검사기는 내부적으로 allow 또는 block 의미를 반환해도 되지만, Claude wrapper와 Codex wrapper가 각 런타임 스키마로 변환한다.",
    "- hook stdout에는 반드시 단일 JSON 한 줄만 출력한다.",
    "- 로그, 디버그, 검증 명령 출력은 stderr로만 보낸다.",
    "",
    "참고한 설계:",
    "- Yeachan-Heo/oh-my-codex의 native Stop continuation 아이디어를 참고한다.",
    "- Stop hook은 작업이 끝났는지 묻는 검문소가 아니라, 남은 작업이 있으면 block으로 계속 진행하게 하는 장치다.",
    "- 상태는 processing, finished, blocked, failed, askuserQuestion lifecycle을 구분한다.",
    "",
    "목표:",
    "- 새 사용자 요청이 들어오면 작업 상태를 processing으로 기록한다.",
    "- 에이전트가 답변을 끝내기 직전에는 Stop hook이 완료 증거를 검사한다.",
    "- 남은 계획, 진행 중 항목, 미완료 작업이 보이면 block으로 멈춤을 막고 계속 작업하게 한다.",
    "- 남은 작업이 없다고 판단되면 status를 finished로 바꾸고 Stop hook이 통과하게 한다.",
    "- status가 finished이면 Stop hook은 다시 block하지 않는다.",
    "- 사용자의 추가 판단이 필요하면 askuserQuestion 상태로 바꾸고 block하지 않는다.",
    "- hook payload에 마지막 응답이나 transcript_path가 없으면 무조건 block하지 말고, 런타임별 fallback 정책을 둔다.",
    "",
    "만들 파일:",
    "- .claude/settings.local.json",
    "- .claude/settings.local.example.json",
    "- scripts/agent-status-start.js",
    "- scripts/agent-stop-check.js",
    "- scripts/agent-stop-output-claude.js",
    "- .agent-status.example.json",
    "- .agent-verification.example.json",
    "- .gitignore 항목: .agent-status.json, .agent-verification.json",
    "- Codex 변형이 필요하면 .codex/hooks.json, .codex/stop-hook.js",
    "",
    "UserPromptSubmit hook:",
    "- 새 요청을 받으면 .agent-status.json을 만든다.",
    "- status는 processing으로 둔다.",
    "- attempts는 0으로 초기화한다.",
    "- max_block_attempts는 3으로 둔다.",
    "- stop_hook_active는 false로 둔다.",
    "- started_at은 ISO 날짜로 둔다.",
    "- 기존 finished 상태가 있더라도 새 사용자 요청이면 processing으로 갱신한다.",
    "- 상태 파일에는 요청 원문, API key, 개인 절대 경로, transcript 전문, 검증 로그 전문을 저장하지 않는다.",
    "",
    "Stop hook:",
    "- .agent-status.json이 없으면 안전하게 processing 상태를 만든다.",
    "- status가 finished, blocked, failed, askuserQuestion 중 하나이면 allow로 통과한다.",
    "- status가 processing이면 마지막 응답, transcript, 상태 파일에서 남은 계획이나 진행 중 작업을 확인한다.",
    "- hook payload에서 transcript_path 또는 마지막 응답을 찾을 수 있으면 그 내용을 검사한다.",
    "- Codex transcript에서는 assistant message와 update_plan 계열 response_item.function_call을 남은 작업 증거로 읽는다.",
    "- 일반 명령 출력과 response_item.function_call_output은 검증 결과 참고에는 쓸 수 있지만, 남은 작업 감지의 주 증거로 삼지 않는다.",
    "- user message와 사용자 프롬프트 원문은 완료 증거에서 제외한다.",
    "- hook payload가 비어 있는 런타임에서는 fallback_policy 상수를 사용한다.",
    "- fallback_policy 기본값은 allow_when_no_remaining_work_signal로 두고, 남은 작업 신호를 확인할 수 없으면 무조건 block하지 않는다.",
    "- pending, in_progress, todo, 미완료, 남은 작업, 다음에 하겠다는 문구가 보이면 block과 이유를 반환하되, Codex wrapper가 최종 block JSON을 Codex 스키마로 보정한다.",
    "- 단, 최종 응답에 남은 작업: 없음, 남은 위험: 없음, no remaining work처럼 명시적 완료 선언이 있으면 그 선언을 남은 작업 감지보다 우선해 allow한다.",
    "- 완료 보고 문장 안에서 hook 동작을 설명하기 위해 남은 작업, 진행 중인 계획 같은 단어를 언급하는 것은 block 근거로 삼지 않는다.",
    "- 완료 증거가 충분하면 status를 finished로 저장하고 allow를 반환한다.",
    "- 외부 입력이 필요하면 status를 askuserQuestion으로 저장하고 allow를 반환한다.",
    "",
    "완료 판단 기준:",
    "- 이 hook의 목적은 특정 검증 명령을 강제하는 것이 아니라 남은 계획이나 작업이 있을 때 계속 진행시키는 것이다.",
    "- 프로젝트별 권장 검증 명령은 상단 상수 RECOMMENDED_VERIFICATION_COMMANDS로 분리하되, 모든 요청에 항상 필수로 강제하지 않는다.",
    "- 현재 요청이 코드 변경, UI 변경, 배포, 파일 생성처럼 검증이 필요한 작업이면 해당 작업에 맞는 검증 결과가 있어야 finished로 볼 수 있다.",
    "- 질문 답변, 설계 설명, 사용자 판단 대기처럼 실행할 작업이 없는 요청은 검증 명령 없이도 finished 또는 askuserQuestion으로 통과할 수 있다.",
    "- 최종 응답 또는 transcript에 남은 작업이 없다는 판단이 있으면 finished로 볼 수 있다.",
    "- 남은 작업 없음 선언과 남은 작업 설명 문구가 같은 응답에 함께 있으면 완료 선언을 우선한다.",
    "- 검증 명령 출력 원문은 상태 파일에 저장하지 않고 transcript나 receipt에서만 확인한다.",
    "",
    "verification receipt fallback:",
    "- transcript 파싱이 불안정한 런타임을 위해 .agent-verification.json receipt를 선택적으로 사용한다.",
    "- receipt에는 completed_steps, recommended_commands, passed_at, git_head, summary, remaining_work만 저장한다.",
    "- receipt에는 API key, 원문 로그, 개인 절대 경로, transcript 전문을 저장하지 않는다.",
    "- Stop hook은 transcript 증거가 부족할 때 receipt를 보조 증거로 확인하되, receipt가 없다는 이유만으로 항상 block하지 않는다.",
    "",
    "loop guard:",
    "- stop_hook_active가 true이면 중복 검문을 막고 allow한다.",
    "- attempts를 block할 때마다 증가시킨다.",
    "- attempts가 max_block_attempts에 도달하면 더 이상 block하지 말고 status를 blocked로 저장한 뒤 allow한다.",
    "- blocked 상태에서는 최종 응답에서 남은 위험과 미완료 검증을 보고하게 한다.",
    "",
    "검증 기준:",
    "- node --check scripts/agent-status-start.js",
    "- node --check scripts/agent-stop-check.js",
    "- Claude용 allow/block JSON 출력 확인",
    "- Codex용 allow/block JSON 출력 확인",
    "- Codex block stdout에 continue:false, decision:allow, systemMessage가 없는지 확인",
    "- stdout이 단일 JSON 한 줄인지 확인",
    "- hook 디버그와 검증 명령 출력이 stderr로만 나오는지 확인",
    "- 빈 payload, transcript_path payload, 남은 작업 감지, receipt fallback, max_block_attempts 도달 케이스를 각각 확인",
    "- 최종 요약에 남은 작업: 없음이 포함된 케이스는 allow되는지 확인",
    "- 실제 남은 작업: npm test 실행 계속 진행 같은 케이스는 block되는지 확인",
    "- .agent-status.json과 .agent-verification.json에 API key, 개인 경로, 민감 로그가 저장되지 않는지 확인",
    "",
    "주의:",
    "- 항상 block하는 Stop hook을 만들지 마라.",
    "- finished, blocked, failed, askuserQuestion 상태에서는 반드시 통과해야 한다.",
    "- 프로젝트별 권장 테스트 명령과 fallback_policy는 상단 상수로 분리하되, hook 목표를 필수 명령 강제가 아니라 남은 작업 감지로 유지해라.",
    "- 상태 파일에는 민감정보를 저장하지 마라.",
    "- .agent-status.json은 런타임 파일이므로 gitignore에 넣고, 공유용 예시는 .agent-status.example.json으로 둔다.",
  ].join("\n"),
};

function buildUnlockArtifact(practice) {
  if (practice.id !== "act6-stop-hook-gate") return undefined;
  return { ...STOP_HOOK_UNLOCK_ARTIFACT };
}

module.exports = {
  buildUnlockArtifact,
};
